// Gamma tables for use with FreeType
// don't edit: this file is generated by crengine/Tools/GammaGen/gammagen.pl
// to rebuild, run perl crengine/Tools/GammaGen/gammagen.pl
//

/***************************************************************************
 *   crengine-ng                                                           *
 *   Copyright (C) 2011 Vadim Lopatin <coolreader.org@gmail.com>           *
 *   Copyright (C) 2022 Aleksey Chernov <valexlin@gmail.com>               *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU General Public License           *
 *   as published by the Free Software Foundation; either version 2        *
 *   of the License, or (at your option) any later version.                *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the Free Software           *
 *   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,            *
 *   MA 02110-1301, USA.                                                   *
 ***************************************************************************/

#ifndef __LVGAMMATBL_H_INCLUDED__
#define __LVGAMMATBL_H_INCLUDED__

#define GAMMA_LEVELS              48
#define GAMMA_NO_CORRECTION_INDEX 15

#ifdef __cplusplus
extern "C" {
#endif

struct lvgammatbl_rec
{
    float gamma;
    const unsigned char* table;
};

extern const struct lvgammatbl_rec lvgammatbl_data[];

#ifdef __cplusplus
}
#endif

#endif // __LVGAMMATBL_H_INCLUDED__
