
set(CMAKE_REQUIRED_DEFINITIONS_BACKUP ${CMAKE_REQUIRED_DEFINITIONS})

set(CMAKE_REQUIRED_DEFINITIONS "-D_LARGEFILE64_SOURCE")
check_symbol_exists(lseek64 "sys/types.h;unistd.h" HAVE_LSEEK64)

set(CMAKE_REQUIRED_DEFINITIONS ${CMAKE_REQUIRED_DEFINITIONS_BACKUP})
